apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devops.redefine.devops.com
spec:
  group: redefine.devops.com
  scope: Namespaced
  names:
    plural: devops
    singular: devops
    kind: DevOps
    shortNames:
      - kubernetes
      - devops
      - ci-cd
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: "Name of the DevOps resource"
                duration:
                  type: string
                  description: "Duration of the DevOps process"
                mode:
                  type: string
                  description: "Mode of the DevOps operation"
                platform:
                  type: string
                  description: "Platform used in the DevOps process"
