apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pod
      namespace: chat-app
      labels:
        app: backend
    spec:
      containers:
        - name: chatapp-backend
          image: batmanlovewonderwomen/chatapp-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: NODE_ENV
              value: production
            - name: MONGODB_URI
              value: "mongodb://mongoadmin:secret@mongodb:27017/chatApp?authSource=admin"
            - name: PORT
              value: "5001"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chatapp-secrets
                  key: jwt-secret
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
