apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-mongo-db-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-mongo-db-app
  template:
    metadata:
      labels:
        app: my-node-mongo-db-app
    spec:
      containers:
        - name: my-node-mongo-db-app
          image: batmanlovewonderwomen/node-mongo-db:01
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_URI

---
apiVersion: v1
kind: Service
metadata:
  name: service-my-node-mongo-db-app
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 3000
  selector:
    app: my-node-mongo-db-app
  type: LoadBalancer
