kind: Deployment
apiVersion: apps/v1
metadata:
  name: vite-deployment
  labels:
    app: vite
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vite
  template:
    metadata:
      labels:
        app: vite
    spec:
      containers:
        - name: vite
          image: batmanlovewonderwomen/myviteapp:02
          ports:
            - containerPort: 5173
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 5173
          readinessProbe:
            httpGet:
              path: /
              port: 5173
